name: pr-gate
on: [pull_request]
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions: {contents: read, pull-requests: write}
    steps:
      - uses: actions/checkout@v4
      - name: Check CODEOWNERS approval
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const number = context.issue.number;
            const query = `
              query ($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $number) {
                    reviewDecision
                  }
                }
              }
            `;
            const result = await github.graphql(query, { owner, repo, number });
            const decision = result.repository.pullRequest?.reviewDecision;
            core.info(`Review decision: ${decision ?? 'UNKNOWN'}`);
            if (decision !== 'APPROVED') {
              core.setFailed('CODEOWNERS approval missing (review decision is not APPROVED).');
            }
      - name: Block auto-merge
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
